import type { Category, EditorKind } from "../simulation/types";
export type Definition = {
  id: Category;
  name: string;
  app: string;
  kind: EditorKind;
  description: string;
  verbs: string[];
  metric: string;
};
export const categories: Definition[] = [
  {
    id: "phone",
    name: "Phone Answering",
    app: "Phone",
    kind: "call",
    description: "Receive calls, document needs, and route a resolution.",
    verbs: [
      "Answer and identify the caller",
      "Record the request and contact details",
      "Resolve, transfer, escalate, or arrange a callback",
    ],
    metric: "customer handling",
  },
  {
    id: "email",
    name: "Email Management",
    app: "Inbox",
    kind: "mail",
    description: "Triage correspondence and write actionable replies.",
    verbs: [
      "Read and organize the message",
      "Write a reply with an owner and deadline",
      "Attach evidence and dispatch",
    ],
    metric: "communication",
  },
  {
    id: "meetings",
    name: "Meetings",
    app: "Calendar",
    kind: "meeting",
    description: "Run an agenda, decide, and assign accountable actions.",
    verbs: [
      "Review the agenda",
      "Respond to the discussion",
      "Record a decision and an action owner",
    ],
    metric: "organization",
  },
  {
    id: "economics",
    name: "Economics",
    app: "Finance",
    kind: "numeric",
    description: "Model price, costs, demand, inflation, and margins.",
    verbs: [
      "Calculate the requested metric",
      "Assess the market change",
      "Recommend a supported pricing action",
    ],
    metric: "analysis",
  },
  {
    id: "finance",
    name: "Finance",
    app: "Finance",
    kind: "numeric",
    description: "Reconcile budgets, cash flow, invoices, and forecasts.",
    verbs: [
      "Calculate the financial result",
      "Explain the variance",
      "Recommend a financial control",
    ],
    metric: "finance",
  },
  {
    id: "accounting",
    name: "Accounting",
    app: "Accounting",
    kind: "ledger",
    description: "Classify transactions and balance the journal.",
    verbs: [
      "Inspect the transaction and invoice",
      "Enter balanced debit and credit entries",
      "Explain the reconciliation",
    ],
    metric: "accuracy",
  },
  {
    id: "research",
    name: "Research",
    app: "Research",
    kind: "research",
    description: "Search company sources and develop an evidenced conclusion.",
    verbs: [
      "Inspect the internal sources",
      "Cite current reliable evidence",
      "Summarize findings and limitations",
    ],
    metric: "research",
  },
  {
    id: "data-analysis",
    name: "Data Analysis",
    app: "Reports",
    kind: "analysis",
    description: "Filter records, chart results, and identify anomalies.",
    verbs: [
      "Explore and compare the dataset",
      "Calculate the requested aggregate",
      "Identify the anomalous record",
    ],
    metric: "analysis",
  },
  {
    id: "spreadsheet",
    name: "Spreadsheet Work",
    app: "Spreadsheet",
    kind: "sheet",
    description: "Build a calculated worksheet from workplace records.",
    verbs: [
      "Enter a working formula in B8",
      "Calculate the requested summary",
      "Save the worksheet as a work artifact",
    ],
    metric: "analysis",
  },
  {
    id: "documents",
    name: "Document Preparation",
    app: "Documents",
    kind: "document",
    description: "Write useful memos, notices, reports, and procedures.",
    verbs: [
      "Write the requested document",
      "Include context, evidence, owner, and deadline",
      "Save a reusable document",
    ],
    metric: "documentation",
  },
  {
    id: "scheduling",
    name: "Scheduling",
    app: "Calendar",
    kind: "calendar",
    description: "Find available time and maintain an accurate calendar.",
    verbs: [
      "Inspect availability",
      "Book a conflict-free appointment",
      "Record attendees and purpose",
    ],
    metric: "organization",
  },
  {
    id: "customer-service",
    name: "Customer Service",
    app: "Customers",
    kind: "case",
    description: "Investigate cases and agree proportionate remedies.",
    verbs: [
      "Verify the customer and case",
      "Choose an authorized remedy",
      "Explain the resolution and follow-up",
    ],
    metric: "customer handling",
  },
  {
    id: "procurement",
    name: "Procurement",
    app: "Vendors",
    kind: "purchase",
    description: "Compare quotes and place an approved purchase order.",
    verbs: [
      "Compare total cost, delivery, and quality",
      "Select a feasible vendor",
      "Record purchase quantity and approval",
    ],
    metric: "finance",
  },
  {
    id: "inventory",
    name: "Inventory",
    app: "Inventory",
    kind: "stock",
    description: "Receive stock, record damage, and prevent shortages.",
    verbs: [
      "Reconcile the physical stock movement",
      "Record the final stock balance",
      "Calculate the reorder quantity",
    ],
    metric: "accuracy",
  },
  {
    id: "hr",
    name: "HR Administration",
    app: "HR",
    kind: "people",
    description: "Maintain onboarding, leave, and training records.",
    verbs: [
      "Verify the employee record",
      "Apply the relevant policy",
      "Record leave or training with approval",
    ],
    metric: "procedure adherence",
  },
  {
    id: "project-management",
    name: "Project Management",
    app: "Projects",
    kind: "board",
    description: "Sequence dependencies and manage delivery risks.",
    verbs: [
      "Resolve prerequisites",
      "Sequence the delivery tasks",
      "Assign a risk response and owner",
    ],
    metric: "organization",
  },
  {
    id: "prioritization",
    name: "Task Prioritization",
    app: "Tasks",
    kind: "rank",
    description: "Order competing work by urgency, impact, and dependencies.",
    verbs: [
      "Inspect deadlines and dependencies",
      "Order the work queue",
      "Explain your first priority",
    ],
    metric: "prioritization",
  },
  {
    id: "communication",
    name: "Professional Communication",
    app: "Chat",
    kind: "chat",
    description: "Give colleagues clear, professional status updates.",
    verbs: [
      "Read the coworker request",
      "Send a factual status update",
      "Commit to a clear next action",
    ],
    metric: "professionalism",
  },
  {
    id: "negotiation",
    name: "Negotiation",
    app: "Vendors",
    kind: "negotiate",
    description: "Negotiate price and delivery within a real mandate.",
    verbs: [
      "Inspect the mandate",
      "Make an offer and respond to a counteroffer",
      "Close an affordable agreement",
    ],
    metric: "communication",
  },
  {
    id: "sales",
    name: "Sales Operations",
    app: "Customers",
    kind: "sales",
    description: "Qualify a lead, quote, and coordinate an order.",
    verbs: [
      "Capture customer requirements",
      "Calculate a valid quotation",
      "Schedule a sales follow-up",
    ],
    metric: "customer handling",
  },
  {
    id: "quality-control",
    name: "Quality Control",
    app: "Reports",
    kind: "quality",
    description: "Audit imperfect records and document corrections.",
    verbs: [
      "Compare the records to the reference",
      "Flag every defective record",
      "Document a corrective action",
    ],
    metric: "accuracy",
  },
  {
    id: "compliance",
    name: "Compliance / Procedures",
    app: "Policies",
    kind: "policy",
    description: "Apply fictional internal policy to workplace situations.",
    verbs: [
      "Consult the relevant policy",
      "Record the required control steps",
      "Route the request to an authorized owner",
    ],
    metric: "procedure adherence",
  },
  {
    id: "incidents",
    name: "Incident Management",
    app: "Tasks",
    kind: "incident",
    description: "Contain disruption, communicate, and restore service.",
    verbs: [
      "Assess the impact and severity",
      "Contain and escalate the incident",
      "Record recovery and communication",
    ],
    metric: "prioritization",
  },
  {
    id: "administration",
    name: "Office Administration",
    app: "Documents",
    kind: "filing",
    description: "Validate, file, and route administrative records.",
    verbs: [
      "Complete the record metadata",
      "Select the correct department",
      "File and send the record",
    ],
    metric: "documentation",
  },
  {
    id: "reporting",
    name: "Reporting",
    app: "Reports",
    kind: "report",
    description: "Turn operational evidence into an accurate report.",
    verbs: [
      "Calculate the operational result",
      "Write findings with evidence",
      "Provide a recommendation and limitations",
    ],
    metric: "documentation",
  },
  {
    id: "presentations",
    name: "Presentations",
    app: "Presentations",
    kind: "slides",
    description: "Build a concise deck and answer audience questions.",
    verbs: [
      "Create at least three purposeful slides",
      "Include calculated evidence and presenter notes",
      "Answer the audience question",
    ],
    metric: "communication",
  },
  {
    id: "operations",
    name: "Operations Management",
    app: "Projects",
    kind: "capacity",
    description: "Allocate limited people to queues and meet service levels.",
    verbs: [
      "Calculate workload capacity",
      "Allocate employees across queues",
      "Explain bottlenecks and tradeoffs",
    ],
    metric: "analysis",
  },
  {
    id: "decisions",
    name: "Business Decision Making",
    app: "Reports",
    kind: "decision",
    description: "Review business records and commit to a justified decision.",
    verbs: [
      "Compare return and risk",
      "Select an approach within constraints",
      "Document the decision and mitigation",
    ],
    metric: "analysis",
  },
  {
    id: "time-management",
    name: "Time Management",
    app: "Tasks",
    kind: "time",
    description: "Schedule focused work around interruptions and deadlines.",
    verbs: [
      "Sequence the workday",
      "Allocate time to the top priority",
      "Respond to the interruption",
    ],
    metric: "time management",
  },
  {
    id: "workday",
    name: "Full Workday Simulation",
    app: "Dashboard",
    kind: "day",
    description: "Run a complete generated shift across the company.",
    verbs: [
      "Launch and work through the generated assignments",
      "Resolve calls, messages, and deadlines",
      "Submit the end-of-day review",
    ],
    metric: "time management",
  },
];
export const definition = (id: string) => categories.find((c) => c.id === id);
export const levels = [
  "Orientation",
  "Junior Apprentice",
  "Apprentice",
  "Advanced Apprentice",
  "Junior Employee",
  "Independent Worker",
];
export const level = (xp: number) => Math.min(5, Math.floor(xp / 350));
export const applications = [
  "Dashboard",
  "Inbox",
  "Phone",
  "Chat",
  "Calendar",
  "Tasks",
  "Projects",
  "Finance",
  "Accounting",
  "Research",
  "Spreadsheet",
  "Documents",
  "Reports",
  "Presentations",
  "Customers",
  "Vendors",
  "Inventory",
  "HR",
  "Policies",
  "Performance",
];
